### ISSUE TITLE
OffTop - BlockHunt

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Ad5001/HideAndSeek#3]
*Add me on Twitter, @Twertik_ .
 I didn't really like the implementation of the plugin... That's mcg76 was the best BlockHunt (HideAndSeek). If you could write the same!!!
Here is a link to the video: https://youtu.be/qZiXigm7EhY

**Comment by Ad5001** [comment]
I cannot "write the same" because this plugin is not a BlockHunt. It's an HideAndSeek one.
It's much complicated of making dynamic backups. For this, you can use an another plugin because it's not the point of this plugin.
Plus I don't see what's missing: it starts automaticly after 75% of the max players has joined.  Or you can force start it if there aren't enought players.

Btw I tried creating signs but I don't see the point of remaking an another sign system while a lot exists on the internet.

Thought if you have aény question about how does this plugin works, you can email me at mail@ad5001.eu
